from pathlib import Path

from fastapi.testclient import TestClient

from src.api.main import app

client = TestClient(app)


def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_validate_endpoint_passes():
    payload = {
        "sku": "X1",
        "name": "Test",
        "attributes": [
            {"key": "operating_pressure_bar", "label": "Operating Pressure", "value": 150},
            {"key": "burst_pressure_bar", "label": "Burst Pressure", "value": 700},
        ],
    }
    response = client.post("/validate/", json=payload)
    assert response.status_code == 200
    assert response.json()["passed"] is True


def test_validate_endpoint_fails():
    payload = {
        "sku": "X2",
        "name": "Test",
        "attributes": [
            {"key": "operating_pressure_bar", "label": "Operating Pressure", "value": 150},
            {"key": "burst_pressure_bar", "label": "Burst Pressure", "value": 200},
        ],
    }
    response = client.post("/validate/", json=payload)
    assert response.status_code == 200
    assert response.json()["passed"] is False


def test_products_endpoint_returns_503_without_neo4j():
    response = client.get("/products/ANYTHING")
    assert response.status_code == 503


def test_ingest_upload_with_sample_pdf():
    sample = Path("data/raw_catalogs/sample_hydraulic_fitting.pdf")
    if not sample.exists():
        return  # generated by scripts/generate_sample_pdf.py; skip if absent
    with sample.open("rb") as fh:
        response = client.post(
            "/ingest/upload", files={"file": (sample.name, fh, "application/pdf")}
        )
    assert response.status_code == 200
    body = response.json()
    assert body["product"]["sku"] == "SAMPLE_HYDRAULIC_FITTING"
    assert len(body["product"]["attributes"]) > 0


def test_root_serves_html():
    response = client.get("/")
    assert response.status_code == 200
    assert "text/html" in response.headers.get("content-type", "")
    assert "Omni-Graph" in response.text


def test_ui_rules_meta():
    response = client.get("/api/rules-meta")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)
    assert len(data) >= 5
    rule_names = [r["name"] for r in data]
    assert "pressure_safety_margin" in rule_names


def test_ui_demo_products():
    response = client.get("/api/demo-products")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)
    assert len(data) >= 2
    skus = [p["sku"] for p in data]
    assert "DEMO-001" in skus


def test_auth_google():
    response = client.post("/api/auth/google", json={"email": "engineer@google.com", "name": "Google Tester"})
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "success"
    assert "token" in data
    assert data["user"]["email"] == "engineer@google.com"


def test_auth_email():
    response = client.post("/api/auth/login", json={"email": "sarah.connor@cyberdyne.io", "name": "Sarah Connor"})
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "success"
    assert data["user"]["name"] == "Sarah Connor"


def test_user_profile():
    get_res = client.get("/api/user/profile")
    assert get_res.status_code == 200
    profile = get_res.json()
    assert "name" in profile
    assert "api_key" in profile

    put_res = client.put("/api/user/profile", json={"department": "Advanced Fluid Power R&D"})
    assert put_res.status_code == 200
    updated = put_res.json()
    assert updated["user"]["department"] == "Advanced Fluid Power R&D"


